name: adapter
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.3
  - aiosignal=1.4.0
  - async-timeout=5.0.1
  - attrs=25.4.0
  - backports.zstd=1.3.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - certifi=2026.1.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - cryptography=46.0.5
  - cyrus-sasl=2.1.28
  - daiquiri=3.0.0
  - exceptiongroup=1.3.1
  - frozenlist=1.7.0
  - greenlet=3.3.1
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - iniconfig=2.3.0
  - iso8601=2.1.0
  - isodate=0.7.2
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.45.1
  - libedit=3.1.20250104
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - liblzma=5.8.2
  - libnsl=2.0.1
  - libntlm=1.8
  - libpq=18.1
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lxml=6.0.2
  - multidict=6.7.0
  - ncurses=6.5
  - openldap=2.6.10
  - openssl=3.6.1
  - packaging=26.0
  - pendulum=2.1.2
  - pip=26.0.1
  - pluggy=1.6.0
  - propcache=0.3.1
  - psycopg2=2.9.11
  - pyasn1=0.6.2
  - pycparser=2.22
  - pygments=2.19.2
  - pyjwt=2.11.0
  - pyparsing=3.3.2
  - pysocks=1.7.1
  - pytest=9.0.2
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-json-logger=2.0.7
  - python_abi=3.11
  - pytz=2025.2
  - pytzdata=2020.1
  - rdflib=7.5.0
  - readline=8.3
  - requests=2.32.5
  - requests-toolbelt=1.0.0
  - setuptools=82.0.0
  - six=1.17.0
  - sqlalchemy=1.4.46
  - sqlite=3.51.2
  - tk=8.6.13
  - tomli=2.4.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.6.3
  - wheel=0.46.3
  - yarl=1.22.0
  - zstd=1.5.7
  - pip:
      - dataone-common==3.5.2
      - dataone-libclient==3.5.2
      - pyxb-x==1.2.6.3
      - zipstream==1.1.4
prefix: /home/servilla/miniconda3/envs/adapter
