name: adapter
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - async-timeout=5.0.1
  - attrs=25.3.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - colorama=0.4.6
  - cryptography=45.0.7
  - cyrus-sasl=2.1.28
  - daiquiri=3.0.0
  - exceptiongroup=1.3.0
  - frozenlist=1.7.0
  - greenlet=3.2.4
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - iniconfig=2.0.0
  - iso8601=2.1.0
  - isodate=0.7.2
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libiconv=1.18
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libntlm=1.8
  - libpq=17.6
  - libsqlite=3.50.4
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - lxml=6.0.1
  - multidict=6.6.3
  - ncurses=6.5
  - openldap=2.6.10
  - openssl=3.5.2
  - packaging=25.0
  - pendulum=2.1.2
  - pip=25.2
  - pluggy=1.6.0
  - propcache=0.3.1
  - psycopg2=2.9.10
  - pyasn1=0.6.1
  - pycparser=2.22
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - pytest=8.4.1
  - python=3.11.13
  - python-dateutil=2.9.0.post0
  - python-json-logger=2.0.7
  - python_abi=3.11
  - pytz=2025.2
  - pytzdata=2020.1
  - rdflib=7.1.4
  - readline=8.2
  - requests=2.32.5
  - requests-toolbelt=1.0.0
  - setuptools=80.9.0
  - six=1.17.0
  - sqlalchemy=1.4.46
  - sqlite=3.50.4
  - tk=8.6.13
  - tomli=2.2.1
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wheel=0.45.1
  - yarl=1.20.1
  - zstandard=0.24.0
  - zstd=1.5.7
  - pip:
      - dataone-common==3.5.2
      - dataone-libclient==3.5.2
      - pyxb-x==1.2.6.3
      - zipstream==1.1.4
prefix: /home/servilla/miniconda3/envs/adapter
